name: Testing first Pipeline

on: workflow_dispatch
jobs:
  myfirst_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.3
      - name: folder status  
        run: ls -a
      
