name: Terraform workflow

on: workflow_dispatch

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    name: matrix-job
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Hello Prakash"
        
  

